apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
        - name: webapi-container
          image: nikhilborgave/emartapp-javaapi:latest
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://emartdb-service:3306/books?useSSL=false&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 9000
